pipeline:

  clone_theme:
    image: plugins/git
    commands:
      - git clone --depth 1 https://github.com/waylayio/waylay-hugo-theme.git themes/waylay

  build:
    image: webhippie/hugo:latest
    commands:
      - hugo

  docker:
    image: plugins/docker
    registry: eu.gcr.io
    repo: eu.gcr.io/quiet-mechanic-140114/documentation
    username: _json_key
    tag: latest
    when:
      branch: master
      event: push

  deploy:
    image: google/cloud-sdk
    pull: true
    commands:
      # authenticate to Kubernetes with the "drone" Service Account
      - printenv KUBE_SERVICE_ACCOUNT > credentials.json
      - gcloud auth activate-service-account --key-file=credentials.json
      - "gcloud container clusters get-credentials production \
        --zone europe-west1-d \
        --project quiet-mechanic-140114"
      # since we can't force a rolling update when the .spec.template hasn't changed
      # we'll just scale down and back up to refresh the pods
      - kubectl scale deployments/documentation --replicas=0
      - kubectl scale deployments/documentation --replicas=1
    when:
      status: success

  slack:
    image: plugins/slack
    webhook: https://hooks.slack.com/services/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
    channel: ci
    username: drone
    icon_url: https://rawcdn.githack.com/drone/brand/master/logos/png/drone-logo_256.png
    when:
      status: changed
