pipeline:

  clone_theme:
    image: plugins/git
    commands:
      - git clone https://github.com/gillesdemey/waylay-hugo-theme.git themes/waylay

  build:
    image: webhippie/hugo:latest
    commands:
      - hugo

  docker:
    image: plugins/docker
    registry: eu.gcr.io
    repo: eu.gcr.io/quiet-mechanic-140114/documentation
    username: _json_key
    tag: latest
    when:
      branch: master
      event: push

  deploy:
    image: google/cloud-sdk
    commands:
      # authenticate to Kubernetes with the "drone" Service Account
      - printenv KUBE_SERVICE_ACCOUNT > credentials.json
      - gcloud auth activate-service-account --key-file=credentials.json
      - "gcloud container clusters get-credentials staging \
        --zone europe-west1-d \
        --project quiet-mechanic-140114"
      # https://github.com/kubernetes/kubernetes/issues/30617
      - export GOOGLE_APPLICATION_CREDENTIALS=credentials.json
      # since we can't force a rolling update when the .spec.template hasn't changed
      # we'll just scale down and back up to refresh the pods
      - kubectl scale deployments/documentation --replicas=0
      - kubectl scale deployments/documentation --replicas=1
    when:
      status: success
