pipeline:

  clone_theme:
    image: plugins/git
    commands:
      - git clone https://github.com/gillesdemey/waylay-hugo-theme.git themes/waylay

  build:
    image: webhippie/hugo:latest
    commands:
      - hugo --baseUrl http://130.211.103.225/

  docker:
    image: plugins/docker
    registry: eu.gcr.io
    repo: eu.gcr.io/quiet-mechanic-140114/documentation
    username: _json_key
    tag: latest
    when:
      branch: master
      event: push

  deploy:
    image: google/cloud-sdk
    commands:
    - kubectl set image deployment/documentation documentation=eu.gcr.io/quiet-mechanic-140114/documentation:latest
    when:
      status: success
