pipeline:

  clone_theme:
    image: plugins/git
    commands:
      - git clone https://github.com/gillesdemey/waylay-hugo-theme.git themes/drone

  build:
    image: webhippie/hugo:latest
    commands:
      - hugo

  docker:
    image: plugins/docker
    registry: eu.gcr.io
    repo: eu.gcr.io/quiet-mechanic-140114/documentation
    username: _json_key
    tag: latest
    when:
      branch: master
      event: push
