title: "Waylay.io Documentation"
baseURL: "https://docs.waylay.io/"
theme: "waylay"

defaultContentLanguage: en
copyright: Copyright © 2017 Waylay BVBA

params:
  supportEmail: support@waylay.io

menu:
  main:
    - identifier: documentation
      weight: 1
      name: Documentation
      url: /

    - identifier: tutorial
      weight: 2
      name: Tutorials
      url: /tutorials/

    - identifier: support
      weight: 3
      name: Support
      url: /support/

    - identifier: plugin
      weight: 4
      name: Plugins
      url: /plugins/
