title: "Waylay.io Documentation"
baseURL: "https://developers.waylay.io/"
theme: "waylay"

defaultContentLanguage: en
copyright: Copyright © 2017 Waylay BVBA

params:
  supportEmail: support@waylay.io
  algolia_index: waylay
  algolia_key: b0f1edc2d90ee692ed3ee599fc4d7403

menu:
  main:
    - identifier: documentation
      weight: 1
      name: Documentation
      url: /

    - identifier: tutorial
      weight: 2
      name: Tutorials
      url: /tutorials/

    - identifier: support
      weight: 3
      name: Support
      url: /support/

    - identifier: plugin
      weight: 4
      name: Plugins
      url: /plugins/
