title: "Waylay.io Documentation"
baseURL: "https://developers.waylay.io/"
theme: "waylay"

defaultContentLanguage: en
copyright: Copyright © 2017 Waylay NV

params:
  supportEmail: support@waylay.io
  algolia_index: waylay
  algolia_key: b0f1edc2d90ee692ed3ee599fc4d7403
  search: true # API docs search feature
  language_tabs:
    - key: shell
      name: cURL
    - key: javascript
      name: JavaScript

menu:
  main:
    - identifier: documentation
      weight: 1
      name: Documentation
      url: /

    - identifier: tutorial
      weight: 2
      name: Tutorials
      url: /tutorials/

    - identifier: labs
      weight: 3
      name: Labs
      url: http://labs.waylay.io

    - identifier: videos
      weight: 4
      name: Videos
      url: https://www.youtube.com/watch?v=oHGSCq1m9DE&list=PLy54mo7VaB1hMsaTA6gVYn2XJSov3dnSK

    - identifier: plugin
      weight: 5
      name: Plugins
      url: /plugins/
