title: "Waylay.io Documentation"
baseURL: "https://developers.waylay.io/"
theme: "waylay"

defaultContentLanguage: en
copyright: Copyright © 2017 Waylay NV

googleAnalytics: "UA-50877508-2"


params:
  supportEmail: support@waylay.io
  algolia_index: waylay
  algolia_key: b0f1edc2d90ee692ed3ee599fc4d7403
  search: true # API docs search feature
  language_tabs:
    - key: shell
      name: cURL
    - key: javascript
      name: JavaScript

taxonomies:
  tag: tags
  category: categories
  series: series

menu:
  main:
    - identifier: documentation
      weight: 1
      name: Documentation
      url: /

    - identifier: labs
      weight: 2
      name: Labs
      url: http://labs.waylay.io

    - identifier: videos
      weight: 3
      name: Videos
      url: https://www.youtube.com/watch?v=oHGSCq1m9DE&list=PLy54mo7VaB1hMsaTA6gVYn2XJSov3dnSK

   # - identifier: plugin
   #   weight: 4
   #   name: Plugins
   #   url: /plugins/
